/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dos;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
/**
 *
 * @author seabirds
 */
public class FeatureFrame extends javax.swing.JFrame {

    /**
     * Creates new form FeatureFrame
     */
    DefaultListModel dm1=new DefaultListModel();
    DefaultListModel dm2=new DefaultListModel();
    ArrayList feat=new ArrayList();
    MainFrame mf;
    Details dt=new Details();
    
    public FeatureFrame(MainFrame me) 
    {
        initComponents();
        mf=me;
        displayFeature();
    }

    public void displayFeature()
    {
        try
        {
                               
            jList1.setModel(dm1);            
            jList2.setModel(dm2);
            
            String g1[]=mf.dataList.get(0).toString().split("\t");
            for(int i=0;i<g1.length;i++)
            {
                 dm1.addElement(g1[i].trim());
                 feat.add(g1[i].trim());
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setText("Feature Selection");

        jList1.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jList2.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList2);

        jButton1.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        jButton1.setText(">>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        jButton2.setText("<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jButton3.setText("Encode Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(272, 272, 272))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            if(jList1.getSelectedIndex()!=-1)
            {
                dm2.addElement(jList1.getSelectedValue());
                dm1.removeElementAt(jList1.getSelectedIndex());
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Select Features");
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            if(jList2.getSelectedIndex()!=-1)
            {
                dm1.addElement(jList2.getSelectedValue());
                dm2.removeElementAt(jList2.getSelectedIndex());
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Select Features to Remove");
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            int sz=dm2.getSize();
            if(sz==0)
                JOptionPane.showMessageDialog(this,"Add Features");
            else
            {
                ArrayList at1=new ArrayList();
                for(int i=0;i<sz;i++)
                {
                    at1.add(dm2.getElementAt(i).toString().trim());
                }
                
                int flag=0;
                for(int i=0;i<dt.features.length;i++)
                {
                    String g1=dt.features[i];
                    if(!at1.contains(g1))
                    {
                        flag=1;
                        break;
                    }
                }
                if(flag==1)
                {
                    JOptionPane.showMessageDialog(this,"Must Select the following Features\n"
                            + "duration,protocol_type,service,flag,src_bytes,dst_bytes and class");
                }
                else
                {
                    System.out.println("at1 "+at1);
                    System.out.println("data  "+mf.dataList.get(0));
                    
                    
                    
                    String g4[]=mf.dataList.get(0).toString().split("\t");
                    String ft="";
                    for(int j=0;j<g4.length;j++)
                    {
                        if(at1.contains(g4[j].trim()))
                        {
                            ft=ft+g4[j].trim()+"\t";
                                
                        }
                    }
                    ft=ft.trim()+"\n";
                    
                    String g5[]=mf.dataList.get(1).toString().split("\t");
                    String ft1="";
                    for(int j=0;j<g5.length;j++)
                    {
                        if(at1.contains(g4[j].trim()))
                        {
                            ft1=ft1+g5[j].trim()+"\t";
                                
                        }
                    }
                    ft1=ft1.trim()+"\n";
                    
                    
                    String txt="";
                    
                    
                    for(int i=2;i<mf.dataList.size();i++)
                    {
                        String g1[]=mf.dataList.get(0).toString().trim().split("\t");
                        String g2[]=mf.dataList.get(i).toString().trim().split("\t");
                        String g3="";
                        
                        for(int j=0;j<g1.length;j++)
                        {
                            if(at1.contains(g1[j].trim()))
                            {
                               
                                g3=g3+g2[j].trim()+"\t";
                                
                            }
                        }
                        txt=txt+g3.trim()+"\n";
                        
                    }
                    
                    String data1=ft+ft1+txt;
                    System.out.println(data1);
                    
                    
                    
                    DataFrame df=new DataFrame(data1);
                    DefaultTableModel dm=(DefaultTableModel)df.jTable1.getModel();
                    String s1[]=data1.split("\n");
                    String s2[]=s1[0].split("\t");
                    dm.setColumnIdentifiers(s2);
                    
                    for(int i=2;i<s1.length;i++)
                    {
                        String g1[]=s1[i].split("\t");
                        Vector v=new Vector();
                        for(int j=0;j<g1.length;j++)
                        {
                            v.add(g1[j]);
                        }
                        dm.addRow(v);
                    }
                    
                    int row=dm.getRowCount();
                    System.out.println("row "+row);
                    
                    String s3[]=s1[1].split("\t");
                    for(int i=0;i<s3.length-1;i++)
                    {
                        if(s3[i].equals("sym"))
                        {
                             ArrayList at=new ArrayList();
                             for(int j=0;j<row;j++)
                             {
                                String g1=dm.getValueAt(j, i).toString();
                                if(!at.contains(g1))
                                    at.add(g1);
                             }
                             System.out.println(at);
                             
                            for(int j=0;j<row;j++)
                            {
                                String g1=dm.getValueAt(j, i).toString();
                                String ss1="";
                                for(int k=0;k<at.size();k++)
                                {
                                    if(at.get(k).equals(g1))
                                    {
                                        ss1=ss1+"1";
                                    }
                                    else
                                        ss1=ss1+"0";
                                }                        
                        
                                int d1=Integer.parseInt(ss1,2);
                                System.out.println(ss1+" : "+d1+" : "+g1);
                                dm.setValueAt(d1, j, i);
                            }
                        }
                        
                    }
                    
                    df.setTitle("Encoded Data");
                    df.setResizable(false);
                    df.setVisible(true);
                   /* String s1[]=data1.split("\n");
                    String s2[]=s1[1].split("\t");
                    */
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new FeatureFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
